language: go

go:
  - "1.14.x"

install: true

#before_script:
#- go get github.com/golangci/golangci-lint/cmd/golangci-lint


script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - make build




